name: Natural Computing Group
url: https://naco.liacs.nl
author: "Niki van Stein"

exclude: [bibble, README.md, Makefile, screenshot.png, vendor/, node_modules/, 'accept/', 'foga2025/']

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: pretty

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: prof
    name: Group leader
  - key: aprof
    name: Assistant and Associate Professors
  - key: staff
    name: Staff
  - key: postdoc
    name: Post Doctoral Researchers
  - key: grad
    name: Graduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni


event_types:
  - key: conference
    name: Conferences
  - key: workshop
    name: Workshops and Special Sessions
  - key: tutorial
    name: Tutorials

# Number of news stories on the front page.
front_page_news: 3

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true
  groups:
    output: true
  events:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research/
  - title: Events
    link: /events/
  # - title: Education
  #   link: /education.html
  - title: Contact
    link: /contact/


# Social Sharing
twitter:
  username               : &twitter "naco_liacs"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  'og-image.png'
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : 'Organization' # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

plugins:
  - jekyll-sitemap

compress_images:
  images_path: "/img/**/*.{gif,png,jpg,jpeg,svg}"
